---
version: "3.6"

services:
  chargen2pd:
    build: .
    image: chargen2pd
    environment:
      - LISTEN_ADDR=tcp:0.0.0.0:19
      - MAX_CONNS=10
      - CONN_TIMEOUT=10
      - LOG_PER_CONNECTION=true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - 19
